export const FETCH_ALL_DATA = 'FETCH_ALL_DATA'
export const FETCH_ALL_DATA_SUCCESS = 'FETCH_ALL_DATA_SUCCESS'
export const FETCH_ALL_DATA_ERROR = 'FETCH_ALL_DATA_ERROR'
export const FETCH_DATA_BY_ID = 'FETCH_DATA_BY_ID'
export const FETCH_DATA_BY_ID_ERROR = 'FETCH_DATA_BY_ID_ERROR'
export const FETCH_DATA_BY_ID_SUCCESS = 'FETCH_DATA_BY_ID_SUCCESS'

