export const FETCH_ALL_DATA = 'FETCH_ALL_DATA'
export const FETCH_ALL_CHARACTERS_SUCCESS = 'FETCH_ALL_CHARACTERS_SUCCESS'
export const FETCH_ALL_EPISODES_SUCCESS = 'FETCH_ALL_EPISODES_SUCCESS'
export const FETCH_ALL_DATA_ERROR = 'FETCH_ALL_DATA_ERROR'
export const FETCH_CHARACTER_BY_ID_SUCCESS = 'FETCH_CHARACTER_BY_ID_SUCCESS'
export const FETCH_EPISODES_BY_ID = 'FETCH_EPISODES_BY_ID'
export const GET_ALL_SEASONS = 'GET_ALL_SEASONS'
export const GET_SEASON_BY_ID = 'GET_SEASON_BY_ID'

